### DISCUSSION TITLE
Documentation and website branching strategy

### DISCUSSION THREAD

**Discussion by johnnovak** [dosbox-staging/dosbox-staging#2411] [General]
## Current state

The website and the upcoming getting started guide and the documentation are generated from the same MkDocs source tree. In other words, whenever we kick off the [Deploy website GitHub action](https://github.com/dosbox-staging/dosbox-staging/actions/workflows/deploy-website.yml), that actually re-generates and deploys both the website _and_ the documentation.

This makes sense as the website and the documentation are kind of intertwined, e.g. the site-wide search works across the documentation, the getting started guide, the release notes, and the rest of the site. If we will add a blog in the future, the search will find stuff in blog entries too (MkDocs Material [has added blog support recently](https://squidfunk.github.io/mkdocs-material/blog/), but it's still a [paid feature](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/) that will become free later).

Overall, not separating the website and the doco has important benefits:

- it makes site-wide search possible
- it makes maintaining the website easier (design is shared between the doco & the actual site)
- it simplifies deploys

## Lifecycles

Different parts of our website have different lifecycles:

- **Documentation:** The documentation has generally the same lifecycle as the releases themselves; they should be generally updated in lockstep. In some cases, however, we might want to make corrections to the current documentation between releases (we don't want to wait 3-6 months for doco fixes to become available).

- **Getting Started guide:** This should be pretty static and should need only occasional updates when fixing errors or making adjustments to it. Its lifecycle is largely decoupled from the release lifecycle, but also somewhat coupled to it (e.g., if we need to adjust the guide when some feature has been deprecated).

- **Rest of the website:** Currently, similar to the documentation lifecycle. We make major updates to the website on each release (e.g., update the feature highlights; bump the version on the front page; add new release notes), but we sometimes need to fix typos, correct links, etc. between releases. Now, if we add a blog in the future, then the website itself would see more frequent updates (depending on how often we post new content 😎), so it might become _very_ decoupled from the release lifecycle.

## Goals

As mentioned, currently the [Deploy website GitHub action](https://github.com/dosbox-staging/dosbox-staging/actions/workflows/deploy-website.yml) deploys the whole website from the `main` branch. This needs some enhancements because of the lifecycle issues outlined above.

The high-level goals are as follows:

- **Ability to view the current work-in-progress documentation for the next release somewhere.** Not everybody wants to go through the hassle of installing MkDocs locally, so it would be best if the current WIP doco would be available at some hidden URL on our website.

- **Ability to merge documentation changes to main, just like regular code-change PRs.** We definitely _do not want_ long-lived documentation branches for the next release! Documentation changes should ideally be made in lockstep with the PRs that change existing functionality / introduce new  features. The best outcome would be to get into the habit of updating the doco and the code in a __single__ PR in lockstep! (Not always applicable for experimental / WIP features, but a nice goal to strive towards to, nevertheless.)

- **Ability to make changes to any part of the website (including the doco) outside of the release lifecycles.** This is important, and more common than one would first think. There are always typos, inaccuracies, omissions, wrong information, and broken links—we don't want to wait until the next release to deploy the fixes to these.

- **Keep it all simple!** We don't want to make the whole website and doco release/update process complicated, difficult, and error-prone to use. Let's try to do the simplest thing that works!

### Floating tags

The simplest solution I can think of is to use a floating `docs` tag for the current release. `main` would naturally always contain the current work-in-progress version of the website and the doco that will become online when we publish the next release. When we need to "backport" doco stuff from `main`, or just need to fix things on the current site, we fix that in our "point release", plus cherry-pick it to main as well, then we set the floating `docs` tag to our "point release" branch (e.g. `v.0.81.1`).

The benefit of this approach is that the deploy website action never needs to be modified; the deploy action would always do the following fixed steps:

- Deploy website from the `docs` tag to `https://dosbox-staging.github.io/dev/` (note the `dev` prefix)
- Deploy website from `main` to `https://dosbox-staging.github.io/`

The drawback of this approach is that some people don't like floating tags 😄 But I can't think of anything else; it just needs a little minimal coordination to use it properly.

###  Using release tags

A variation of the above is to simply use the release tags without the "symbolic alias" offered by the floating `docs` tag. This would certainly work and would avoid the drawbacks of floating tags. The only drawback of this approach is that the release tag to use for the current website needs to be modified in the deploy website action. Alternatively, this could be stored as a [repo level variable](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository); this is probably the best solution but I haven't tried it personally yet.

**Comment by johnnovak** [comment]
My view: I liked the floating tags best, but as I finished the writeup, I realised the "release tags" approach is probably best in conjunction with a repo-level variable that stores the branch/tag name of the current release.

If suggesting any alternative solutions, please think through the various use-cases carefully and consider all lifecycles (e.g. we've just released a new version, then made some substantial changes to the doco in `main` but that should only become online 6 months from now. Somebody flagged a number of issues with our current doco and reported broken links in our release notes just now. What then?)

**Comment by kcgen** [comment]
Thanks for the detailed explanation, @johnnovak. I like the prefixes, and was wondering if it's possible to have long-lived doc trees? 

- dosbox-staging.github.io/blog/ <- rolling blog, always up-to-date
- dosbox-staging.github.io/docs/main/ <- rolling `main` docs, always up-to-date
- dosbox-staging.github.io/docs/0.82/ <- long-lived 82.x series docs
- dosbox-staging.github.io/docs/0.81/ <- long-lived 81.x series docs
- dosbox-staging.github.io/docs/0.80/ <- long-lived 80.x series docs

---

Regarding how we trigger the generation, ideally it could "on-change" without needing a floating tags (one less thing to remember).

Some examples with CI snippets:

### Blog

- If *any* PR is merged to `main` also touches markdown files in the `blog/` subdirectory, then CI should run a workflow to regen the `blog/` entries. 


```yaml
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'blog/**'

jobs:
  regenerate_blog:
    if: github.event.pull_request.merged == true
    run:
      # Regen the blog into .io/blog/...
```

### Latest-`main` docs

- If *any* PR merged to `main` also touches markdown files in the `docs/` subdirectory, then CI should run a workflow to regen the `docs/main/` documentation. 

```yaml
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'docs/**'

jobs:
  regenerate_latest_main_docs:
    if: github.event.pull_request.merged == true
    run:
      # Regen the latest docs into .io/docs/main/
```

### Stable release-series docs

 - if *any* PR merged to the `release/*` branch pattern touches markdown files in the `docs/` subdirectory, then regen the `docs/<tag-version>/` (or `docs/release/`) documentation.

```yaml
on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'
    paths:
      - 'docs/**'

jobs:
  regenerate_release_docs:
    if: github.event.pull_request.merged == true
    run:
      # get the version from the branch's release tag
      version=$(git describe | cut -d '-' -f 1)
      
      # Regen the release docs into .io/docs/$version/
      # (or .io/docs/release/)
```

That's just pseudocode, but looks do-able based on:

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
